name: Build and test packages

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Build source distribution
        run: |
          python -m pip install build
          python -m build --sdist
      - name: Upload source distribution
        uses: actions/upload-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: ./dist/webp-*.tar.gz
          retention-days: 7

  test-sdist:
    name: Test source distribution
    needs: build-sdist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Fetch source distribution
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install the package
        run: |
          python -m pip install dist/webp-*.tar.gz
      - name: Test with pytest
        run: |
          python -m pip install pytest==7.2.1
          pytest tests/

  build-wheels:
    name: Build and test wheels on ${{ matrix.os }}
    needs: build-sdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
    steps:
      - name: Fetch source distribution
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - run: mv dist/webp-*.tar.gz webp.tar.gz
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        with:
          package-dir: webp.tar.gz
          output-dir: dist
        env:
          CIBW_BUILD: 'cp3*-manylinux_x86_64 cp3*-win_amd64 cp3*-macosx_universal2'
          CIBW_ARCHS_MACOS: 'universal2'  # Enable cross-compilation on macOS
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.9,<3.12'
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests
      - uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ github.sha }}
          path: ./dist/*.whl
          retention-days: 7
