name: Build and test packages

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build-sdist:
    name: Build source distribution
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Build source distribution
        run: |
          python -m pip install poetry==1.3.2
          python -m poetry build -f sdist
      - name: Upload source distribution
        uses: actions/upload-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: ./dist/webp-*.tar.gz
          retention-days: 7

  test-sdist:
    name: Test source distribution
    needs: build-sdist
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Fetch source distribution
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install the package
        run: |
          python -m pip install dist/webp-*.tar.gz
      - name: Test with pytest
        run: |
          python -m pip install pytest==7.2.1
          pytest tests/

  build-wheels:
    name: Build and test wheels on ${{ matrix.os }}
    needs: build-sdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            build: 'cp3*-manylinux_x86_64'
          - os: windows-2019
            build: 'cp3*-win_amd64'
          - os: macos-11
            build: 'cp3*-macosx_x86_64'
    steps:
      - name: Fetch source distribution
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - run: mv dist/webp-*.tar.gz webp.tar.gz
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        with:
          package-dir: webp.tar.gz
          output-dir: dist
        env:
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.9,<3.12'
          CIBW_TEST_REQUIRES: pytest
          CIBW_TEST_COMMAND: pytest {package}/tests
      - uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ github.sha }}
          path: ./dist/*.whl
          retention-days: 7

  build-wheels-macos-arm64:
    name: Build arm64 wheels on macos
    needs: build-sdist
    runs-on: macos-11
    steps:
      - name: Fetch source distribution
        uses: actions/download-artifact@v3
        with:
          name: sdist-${{ github.sha }}
          path: dist/
      - run: mv dist/webp-*.tar.gz webp.tar.gz
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        with:
          package-dir: webp.tar.gz
          output-dir: dist
        env:
          CIBW_BUILD: 'cp3*-macosx_arm64'
          CIBW_ARCHS_MACOS: 'arm64'  # Enable cross-compilation
          CIBW_PROJECT_REQUIRES_PYTHON: '>=3.9,<3.12'
      - uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ github.sha }}
          path: ./dist/*.whl
          retention-days: 7
